# <center>초보 투자자들을 위한 가치투자 판단 프로그램</center>

### <div style="text-align: right">  산업경영공학과 </div>
### <div style="text-align: right"> 2017100927 조경모</div>

### 1)프로젝트 목표 및 내용

최근 개인 자산 관리의 한 종류로 주식을 하는 사람들이 굉장히 많아졌다. 하지만, 주식은 복잡한 지표들과 지수들, 
차트를 통해서 공부하기 때문에 초보 투자자들에게는 굉장히 진입장벽이 높다고 할 수 있다. 
따라서 주식을 책으로 통해 공부를 해도 이를 실전 투자에 적용하기는 매우 힘들며, 
개별 종목들을 하나하나 분석하는것도 어려움이 따른다. 때문에 '초보 투자자들을 주식 프로그램이 있다면 
사람들이 좀 더 쉽게 주식에 접근할 수 있지 않을까?'라는 생각이 들었다. 
따라서 아주 기초적인 지표들을 통해 기업 가치를 분석하는 프로그램을 생각해 보았다.
이 프로그램에서 다룰 주식 투자 방법은 '가치 투자'이다. 가치투자란 주식투자의 대가인
피터린치 및 워렌버핏이 지향하는 투자 방법으로, 기업의 미래가치를 분석하고 기업의 
성장 가능성을 보고 직접 투자하는 방식이다. 흔히들 아는 모멘텀 투자 와는 차이가 있는
주식 투자 방법이다. 또한, 이 프로그램에서 대상으로 하는주식은 '채권형 주식'이다. 
채권형 주식이란 사업구조가 매우 안정되어있거나, 이해하기 명확하여 기업의 현금흐름이 예상가능한 기업의 주식을 말한다. 
<br>  
**<center>"주가는 언젠가 기업의 가치를 반영한다"</center>**
<br>
가치투자는 위와 같은 매우 중요한 가정을 바탕으로 한다. 따라서 가치투자에서 가장 중요한것은 '기업의 가치가 얼마만큼 증가할 것인가' 이다. 이때,  '기업의 가치 변화' 에 대해서 재무제표속 다양한 지표를 통해 계산할 수 있다.

하지만 초보 투자자들은 어떤 종목을 분석할건지 쉽게 고를 수 없다. 또한, 자신이 분석하기 위해 선택한 종목은 매우 소수이며, 종목 하나하나를  계산한다면 상당히 많은 시간이 걸릴 것이다.
따라서 이론으로 정리된 기업가치 평가 방식을 파이썬을 통해 개발하여 이용한다면, 훨씬 편리하고 빠르게 종목에 대해서 분석할 수 있을것이다.
결론적으로, 이 프로그램이 지향하는 최종 목표는 초보 투자자들이 이 프로그램의 가치평가를 통해 투자 대상을 선택하는 아이디어를 얻는 것이다.

### 2) 주제 선정 이유 또는 이 프로젝트의 필요성

서준식의 <다시 쓰는 주식 투자 교과서>에 소개된 가치 평가 방법을 토대로 기업의 가치를 계산할 예정이다.<br>


<br>
아래 5단계는 이 책 내용중 채권형 주식 매수 가능 주가 산정 방식이다.  
<br>
1) 채권형 주식의 현재 순자산 가치를 확인한다.<br>
2) 과거의 ROE 추이 관찰 등을 통해 미래 10년간의 평균 ROE를 추정한다.<br>
3) 10년 후 예상되는 채권형 주식의 순자산 가치를 구한다.<br>
4) 3단계에서 구해진 예상 순자산 가치를 목표수익률을 통해 현재가치로 할인한다.<br>
5) 매수 가능 주가보다 현재 주가가 낮을 때 채권형 주식에 투자한다.<br>

위 5단계를 일일이 계산한다면 매우 많은 시간이 소요된다. 따라서 위 5단계를 프로그램을 통해 빠르게 계산하고, 시가총액 상위권의 종목들 중 위 가치판단 방법으로 매수에 적합한 기업들을 추려내 초보 투자자들이 투자 대상을 선별하는 아이디어를 얻을 수 있을 것이다.
또한 위 방법으로 선별된 기업의 사례를 통해 주가의 흐름이 어떻게 변화하는지, 유망한 기업이 어떤 기업인지 과거 데이터를 통해서도 확인해 볼 수 있을 것이다.

### 3) 데이터 획득 방법

이 프로그램 개발을 위해서는 기업 재무제표의 5년간 데이터가 필요하다.
가치 평가에 필요한 지표는 ROE, PER, PBR, EPS, BPS, 평균 ROE로 , [fnguide](http://comp.fnguide.com/SVO2/asp/SVD_Main.asp) 사이트를 크롤링해서 기업 재무제표 데이터를 추출하였다.

ROE 는 자기자본이익률(Return On Equity)로 기업이 자본을 이용하여 얼마만큼의 이익을 냈는지를 나타내는 지표이다. ROE = 당기순이익/자본총액 <br>
PER 은 주가수익비율(Price Earning Ratio)로 현재 주가가 순이익의 몇배 상태인지를 나타내는 지표이다. PER = 주가/주당순이익(EPS) <br>
PBR 은 주가순자산비율(Price Book-value Ratio)로 주가가 주당 순자산의 몇 배로 매매되고 있는가를 보여줍니다. PBR = 주가/주당순자산(BPS) <br>
EPS 는 주당순이익으로(Earning Per Share)로 기업의 현재 순자산을 주식수로 나눈 개념이다. EPS = 당기순이익/총 발행주식수 <br>
BPS 는 주당순자산가치(Book-value Per Share)로 청산가치라고도 부른다. 만약 기업이 지금당장 모든 활동을 중단하고 기업의 자산을 주주들에게 나눠줄 경우, 한 주당 얼마씩 돌아가는지를 나타내는 지표이다. BPS = 기업의 현재 순자산/총 발행주식수<br>
<br>


마지막으로 시가총액 순위별로 정렬된 데이터를 획득해야 하는데, 이를 위해 한국거래소 시가총액 순위를 CSV파일로 다운로드 하였다.

크롤링을 할때, 파이썬 라이브러리인 BeautifulSoup을 이용하였고,  추출된 데이터를 테이블 형태 변환을 위해 pandas 를 이용하였다.

### 4) 구현 내용

우선 위에서 설명한 크롤링을 이용하여 데이터를 획득한다. <br>
모든 종목이 가지고 있는 데이터가 2015~2019년의 데이터 이기 때문에 이 데이터를 이용하여 2020년부터 2025년까지의 EPS, ROE를 계산한다. 이를 통해 미래의 BPS를 계산한다. 미래의 BPS를 데이터를 사용자의 수익률을 이용하여 현재가치로 변환한다. 그 후 계산된 현재가치와 현재 주가를 비교하는데, 현재 주가에 특정 상수값을 곱해서 계산을 하도록 한다. 이 상수값이 클수록 프로그램에 보수적인 입장을 취한다고 가정해야 한다. (그래야만 계산된 현재가치가 부풀려진 값이 아니라고 생각할 수 있기 때문이다).<br>

<br>
프로그램을 구현할시의 실행 예시는 다음과 같다.


처음 사용자에게 <br>
1) 선별한 종목 가치계산<br>
2) 시가총액 상위 100기업 계산<br>
둘 중 하나의 입력을 받아서 진행한다. 
그후, 사용자가 **1)** 을 입력하였다면, 종목코드를 입력 받는다. 그 후엔  (종목이름, 종목코드, 평균 ROE, PER, 업종 PER, 계산된 현재가치, 주가, 평가)와 주가 데이터를 통해  만들어진 이동평균선 차트를 사용자에게 보여준다. 사용자는 이를 통해 이 기업을 매수할 것인지 판단하게 된다.

사용자가 **2)** 를 입력하였다면, 시가총액 상위 100개기업의 
 (종목이름, 종목코드, 평균 ROE, PER, 업종 PER, 계산된 현재가치, 주가, 평가) 를 사용자에게 보여준다. 사용자는 출력돤 데이터를 통해 시가총액 상위 100개 기업 중 자신이 매수하기에 적합한 종목들을 선별하여 분석할 수 있다. 
 이후 **Y**를 입력하였다면, 프로그램에서 선정한 '저평가된 기업'을 확인할 수 있다. 여기서 '저평가된 기업'이란 1)기업 PER이 업종 PER보다 낮고 2)'적합'으로 판정된 기업이다.
 
 
 결론적으로 사용자는 주식 매수를 할때, '적합, 부적합' 판단을 가장 중요하게 참고하여 판단하면 된다. 앞의 다양한 지표들을 계산하여 추출된 결과가 '적합/부적합'이미 떄문이다. 
     이 프로그램은  단순히 각각의 지표를 일일이 확인하는 것이 아니라, 모든 지표들을 결합하여 계산된 결과값을 추출하는 것이기 떄문에 보다 안정적으로 저평가된 주식. 즉, 매수에 적합 한 주식을 선별할 수 있다. 주식 초보자들은 처음 주식 매수를 할때, 종목 선정을 매우 어려워 하는 경우가 많기에 이 프로그램은 이러한 초보자들에게 매우 큰 도움이 될 것이다.

### 5) 분석 결과 또는 구현 결과

In [2]:
import pandas as pd
import numpy as np
import bs4
from openpyxl import load_workbook
from urllib.request import urlopen
import csv
import pandas_datareader as data
from datetime import datetime
from IPython.display import display
import matplotlib.pyplot as plt

pd.set_option('display.max_rows',500)   #row 축약 방지

class stock_evaluation: 
    def get_html(self,jcode):     #재무재표 크롤링
        self.jcode = jcode
        url = 'http://comp.fnguide.com/SVO2/ASP/SVD_main.asp?pGB=1&gicode=A%s' % jcode
        html = urlopen(url).read()
        html = bs4.BeautifulSoup(html,'lxml')
        table = html.find('div',{'id':'highlight_D_Y'})
        crt_data = html.find('div',{'id':'corp_group2'}).find_all('dl')
        self.crt_PER = crt_data[0].find_all('dd')[1].text   #PER
        self.crt_around_PER = crt_data[4].find_all('dd')[1].text   #업종 PER
        self.crt_PBR = float(crt_data[6].find_all('dd')[1].text)
        self.crt_price = int(html.find('span',{'id' : 'svdMainChartTxt11'}).text.replace(',',''))
        self.name = html.find('h1',{'id':'giName'}).text
        
        date_col = table.find_all('tr')[1].find_all('th')[:5]
        date_col=list(i.text for i in date_col) #dataframe의 column

        j = table.find_all('td',{'class','r'})
        tr = table.find_all('tr')[18:]
        self.df = pd.DataFrame()
        
        def get_excel_siga_top(self):  #시가총액 엑셀 read
            load_wb = open('siga.csv','r',encoding='utf-8')
            load_ws = csv.reader(load_wb)
            row_num = 0
            jcode=[]
            for row in load_ws:
                row_num+=1
                if row_num==1:
                    continue
                jcode.append(row[1])
            return jcode
        
    
        for i in tr:        #테이블 항목 가져오기
            category = i.find('span',{'class':'txt_acd'})
            if(category==None):
                category=i.find('th')
            category = category.text.strip()
            value_list = []
            j = i.find_all('td',{'class','r'})[:5]
        
            for value in j:
                temp = value.text.replace(',','').strip()
                try:
                    temp = float(temp)
                    value_list.append(temp)
                except:
                    value_list.append(0)
                data = {category:value_list}
                data = pd.DataFrame(data)
            self.df = pd.concat([self.df,data],axis=1)

        self.df.index=date_col
        return self.df
    
    def get_excel_siga_top(self):  #시가총액 엑셀 read
        load_wb = open('siga.csv','r',encoding='utf-8')
        load_ws = csv.reader(load_wb)
        row_num = 0
        jcode=[]
        for row in load_ws:
            row_num+=1
            if row_num==1:
                continue
            jcode.append(row[1])
        return jcode
    
    def df_extension(self):       #데이터테이블 확장(2025년까지)
        for i in range(6):
            self.ROE_mean = self.df['ROE'].mean()
            new_eps = self.df['BPS'][-1]*self.ROE_mean/100
            new_bps = new_eps + self.df['BPS'][-1]
            PER = self.df['PER'][-1]
            PBR = self.df['PBR'][-1]
            stock_ret = self.df['배당수익률'][-1]
            self.df.loc['202'+str(i)+'/12'] = [self.df['ROA'].mean(),self.ROE_mean,new_eps,new_bps, np.nan, PER, PBR, np.nan, stock_ret]
        return self.df
    
    def report(self):
        self.new_price = int(self.df['BPS'][-1]/((1.15)**5))

        self.all_datas = pd.DataFrame(index = ['종목이름','종목코드','평균ROE','PER','업종PER','현재가치','주가','평가'],
                         data = [self.name,self.jcode,self.ROE_mean,self.crt_PER,self.crt_around_PER,self.new_price,self.crt_price,\
                                 '적합' if self.new_price>=1.5*self.crt_price else '부적합']).T
        return self.all_datas
    
    
    def line(self):        #이평선 그래프 구하기
        start = datetime(2020,5,25)
        end = datetime.now()

        
        kospi_df = data.get_data_yahoo(str(jcode)+'.KS', start, end) 


        new_kospi = kospi_df[kospi_df['Volume'] !=0] #휴장일 제외

        new_kospi['MA5'] = new_kospi['Close'].rolling(5).mean()
        new_kospi['MA20'] = new_kospi['Close'].rolling(20).mean()
        new_kospi['MA60'] = new_kospi['Close'].rolling(60).mean()
        new_kospi['MA120'] = new_kospi['Close'].rolling(120).mean()


        fig, ax = plt.subplots(figsize=(20,10))
        ax.set_title('stock', fontsize=15)
        ax.set_ylabel('stock')
        ax.set_xlabel("Date Time")
        ax.plot(new_kospi.index, new_kospi[['MA5','MA20','MA60','MA120']])
        ax.legend(['MA5','MA20','MA60','MA120'])
        return(plt.show())

    

print("주식종목 가치 평가 프로그램입니다.\n")
se_func = stock_evaluation()
ch1 = input("1. 개별주식종목 조회,  2.시가총액 상위 100개 기업 \n")
report_df = pd.DataFrame()

if(ch1=='1'):
    while(True):
        jcode = input("종목코드를 입력하세요 : ")
        se_func.get_html(jcode)   
        se_func.df_extension() 
        se_func.report()
        report_df = pd.concat([report_df,se_func.all_datas],axis=0)
        report_df.reset_index(drop=True,inplace=True)
        display(report_df)
        se_func.line()
        ch2 = input("계속 조회하려면 Y, else N")
        if(ch2=='n' or ch2=='N'):
            break
        elif(ch2=='Y' or ch2=='y'):
            continue
        else:
            print("key error")
            break


elif(ch1=='2'):
    for i in range(100) : #100개만 조회
        try:
            se_func.get_html(se_func.get_excel_siga_top()[i])
            se_func.df_extension()
            se_func.report()
            report_df = pd.concat([report_df, se_func.all_datas], axis=0)
            report_df.reset_index(drop=True, inplace=True)
        except:
            pass
    display(report_df)

    ch2 = input("프로그램 자체 선별 주식 확인하려면") #저평가된 기업 선별 
    if(ch2=='Y' or ch2=='y'):
        for i in range(len(report_df)):
            if report_df.loc[i]['평가']=='적합' and report_df.loc[i]['PER']<report_df.loc[i]['업종PER']:
                display(pd.DataFrame(report_df.iloc[i]).T)
                
    else:
        print("key error")

주식종목 가치 평가 프로그램입니다.

1. 개별주식종목 조회,  2.시가총액 상위 100개 기업
1
종목코드를 입력하세요 : 011070

    종목이름    종목코드   평균ROE    PER  업종PER   현재가치      주가   평가
0  LG이노텍  011070  5.7836  19.55  19.05  71966  195000  부적합

RemoteDataError: Unable to read URL: https://finance.yahoo.com/quote/011070.KS/history?period1=1590346800&period2=1629658799&interval=1d&frequency=1d&filter=history
Response Text:
b'<!DOCTYPE html>\n  <html lang="en-us"><head>\n  <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n      <meta charset="utf-8">\n      <title>Yahoo</title>\n      <meta name="viewport" content="width=device-width,initial-scale=1,minimal-ui">\n      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\n      <style>\n  html {\n      height: 100%;\n  }\n  body {\n      background: #fafafc url(https://s.yimg.com/nn/img/sad-panda-201402200631.png) 50% 50%;\n      background-size: cover;\n      height: 100%;\n      text-align: center;\n      font: 300 18px "helvetica neue", helvetica, verdana, tahoma, arial, sans-serif;\n  }\n  table {\n      height: 100%;\n      width: 100%;\n      table-layout: fixed;\n      border-collapse: collapse;\n      border-spacing: 0;\n      border: none;\n  }\n  h1 {\n      font-size: 42px;\n      font-weight: 400;\n      color: #400090;\n  }\n  p {\n      color: #1A1A1A;\n  }\n  #message-1 {\n      font-weight: bold;\n      margin: 0;\n  }\n  #message-2 {\n      display: inline-block;\n      *display: inline;\n      zoom: 1;\n      max-width: 17em;\n      _width: 17em;\n  }\n      </style>\n  <script>\n    document.write(\'<img src="//geo.yahoo.com/b?s=1197757129&t=\'+new Date().getTime()+\'&src=aws&err_url=\'+encodeURIComponent(document.URL)+\'&err=%<pssc>&test=\'+encodeURIComponent(\'%<{Bucket}cqh[:200]>\')+\'" width="0px" height="0px"/>\');var beacon = new Image();beacon.src="//bcn.fp.yahoo.com/p?s=1197757129&t="+new Date().getTime()+"&src=aws&err_url="+encodeURIComponent(document.URL)+"&err=%<pssc>&test="+encodeURIComponent(\'%<{Bucket}cqh[:200]>\');\n  </script>\n  </head>\n  <body>\n  <!-- status code : 404 -->\n  <!-- Not Found on Server -->\n  <table>\n  <tbody><tr>\n      <td>\n      <img src="https://s.yimg.com/rz/p/yahoo_frontpage_en-US_s_f_p_205x58_frontpage.png" alt="Yahoo Logo">\n      <h1 style="margin-top:20px;">Will be right back...</h1>\n      <p id="message-1">Thank you for your patience.</p>\n      <p id="message-2">Our engineers are working quickly to resolve the issue.</p>\n      </td>\n  </tr>\n  </tbody></table>\n  </body></html>'

    종목이름    종목코드  평균ROE   PER 업종PER   현재가치     주가  평가
14  KB금융  105560  8.226  6.11  8.00  76220  48450  적합

    종목이름    종목코드  평균ROE   PER 업종PER   현재가치     주가  평가
18  신한지주  055550  8.856  4.90  8.00  66924  34350  적합

   종목이름    종목코드   평균ROE    PER 업종PER    현재가치      주가  평가
20   SK  034730  21.648  21.75  8.00  420197  220000  적합

      종목이름    종목코드 평균ROE   PER 업종PER   현재가치     주가  평가
29  하나금융지주  086790  7.32  4.53  8.00  71914  36100  적합

     종목이름    종목코드   평균ROE    PER  업종PER    현재가치      주가  평가
31  롯데케미칼  011170  15.206  13.85  53.55  447813  289000  적합

    종목이름    종목코드  평균ROE   PER 업종PER   현재가치    주가  평가
39  기업은행  024110  7.506  4.02  4.42  25764  9630  적합

   종목이름    종목코드  평균ROE    PER  업종PER   현재가치     주가  평가
45   KT  030200  5.162  10.16  15.85  37323  24100  적합

           종목이름    종목코드   평균ROE    PER  업종PER   현재가치     주가  평가
68  한국타이어앤테크놀로지  161390  10.612  10.20  53.55  52616  34550  적합

   종목이름    종목코드 평균ROE   PER 업종PER   현재가치     주가  평가
80   GS  078930  10.2  6.55  8.00  83479  37650  적합

    종목이름    종목코드  평균ROE   PER 업종PER    현재가치     주가  평가
92  대림산업  000210  8.998  4.86  6.15  128239  83800  적합

    종목이름    종목코드  평균ROE PER  업종PER    현재가치      주가  평가
94  롯데쇼핑  023530 -2.946   -  28.45  155954  103000  적합